application: alc-landing
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "30d"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$
- ^(.*/)?test$
- ^test/(.*/)?
- ^COPYING.LESSER
- ^README\..*
- \.gitignore
- ^\.git/.*
- \.*\.lint$
- ^fabfile\.py
- ^testrunner\.py
- ^grunt\.js
- ^node_modules/(.*/)?

builtins:
- appstats: on #/_ah/stats/
- remote_api: on #/_ah/remote_api/

handlers:
- url: /admin.*
  script: main.app
  login: admin

- url: /favicon\.ico
  mime_type: image/vnd.microsoft.icon
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /apple-touch-icon\.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png

- url: /apple-touch-icon-precomposed\.png
  static_files: static/apple-touch-icon-precomposed.png
  upload: static/apple-touch-icon-precomposed.png

- url: /(robots\.txt|humans\.txt|crossdomain\.xml)
  static_files: static/\1
  upload: static/(robots\.txt|humans\.txt|crossdomain\.xml)

- url: /img/(.*\.(gif|png|jpg|jpeg))
  static_files: static/img/\1
  upload: static/img/(.*\.(gif|png|jpg|jpeg))

- url: /css/(.*\.(gif|png|jpg|jpeg))
  static_files: static/css/\1
  upload: static/css/(.*\.(gif|png|jpg|jpeg))

- url: /css
  mime_type: text/css
  static_dir: static/css

- url: /data
  mime_type: application/json
  static_dir: static/data

- url: /js
  mime_type: text/javascript
  static_dir: static/js

- url: /fonts
  static_dir: static/fonts

- url: /images
  static_dir: static/images

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "2.5.2"
- name: markupsafe
  version: "0.15"